#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-5"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "796ed32ee02c49599b3ace584f39e517" }
]

[assets]
directory = "./public"
